version: '3.8'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

  ragchain:
    build:
      context: ./ragchain
    env_file:
      - ./ragchain/.env
    depends_on:
      - redis

  backend:
    build:
      context: ./backend
    depends_on:
      - ragchain
    env_file:
      - ./backend/.env.development
    ports:
      - "8080:8080"

volumes:
  redis_data:
