services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

  ragchain:
    build:
      context: ./ragchain
    env_file:
      - ./ragchain/.env
    depends_on:
      - redis

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - ragchain
  frontend:
    build:
      context: ./frontend
    ports:
      - "8443:8443" # nginx port for frontend
    depends_on:
      - backend

volumes:
  redis_data:
